<a href="https://colab.research.google.com/github/GUILLENJV/62f1ab79cc287b001f643389/blob/master/Copia_de_model_6377366a6f84e2001a65fdfe_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#learned embedding encoding for a neural network
from numpy import unique
import numpy
from numpy import array
import pandas as pd
import datetime 
from time import sleep
from tqdm import tqdm
import os
from pandas import read_csv
import json
import tensorflow as tf
from tensorflow import keras
from keras.utils import np_utils
import requests
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from tensorflow.keras.layers import BatchNormalization
from keras.regularizers import l1
from keras.regularizers import l2
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.callbacks import EarlyStopping
from keras.utils.vis_utils import plot_model
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras import regularizers
from matplotlib import pyplot
import matplotlib.pyplot as plt
import seaborn as sns
#from predict import model 
from sklearn import preprocessing
from collections import defaultdict
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from matplotlib import pyplot as plt

In [2]:
# carga los datos
#df = pd.read_excel('631d8277776f1d001a21e6eb.xlsx') 
df = pd.read_csv('6377366a6f84e2001a65fdfe (1).csv')

In [3]:
df["landing_page_id"].value_counts()

62566aa432b19a0164d802be    2019
637735d9b20e47001a2057c1    2019
6377333cb20e47001a2057c0    2019
Name: landing_page_id, dtype: int64

In [4]:
df.head()

_id    landing_pages_group_id  \
0  64c5e4f3-8cd7-4a9b-b373-69c0a2dd1756  6377366a6f84e2001a65fdfe   
1  0f2d1ec7-adcd-482c-985e-6aafc77afe73  6377366a6f84e2001a65fdfe   
2  887c5a9c-652a-488c-901f-a1f6e2610ec5  6377366a6f84e2001a65fdfe   
3  4f33bbf0-3373-48fc-a957-fec5faa948c6  6377366a6f84e2001a65fdfe   
4  271ffac8-16f8-49d8-a0f3-68fe2d54d64d  6377366a6f84e2001a65fdfe   

                campaign_id           landing_page_id  \
0  63594eb49cf1d0001ac4782b  62566aa432b19a0164d802be   
1  6272b7c8b45d5301581d3ddd  62566aa432b19a0164d802be   
2  634da21fd76a550019d0db34  637735d9b20e47001a2057c1   
3  634da151d76a550019d0d9b3  6377333cb20e47001a2057c0   
4  634dd59cd76a550019d0de6c  637735d9b20e47001a2057c1   

          traffic_source_id visitor_device_browser  \
0  61159be7649d1d0359dbb161          Chrome Mobile   
1  5e46d6787810b90011c91204          Chrome Mobile   
2  5e46d6787810b90011c91204                 Safari   
3  5e46d6787810b90011c91204          Chrome Mobile   
4  5e46d6787810b90011c91204       Facebook for iOS   

  visitor_device_hardware_family visitor_device_hardware_model  \
0                         View 3                        B140DL   
1               Galaxy Tab 3 8.0                       SM-T310   
2                      Macintosh                     Macintosh   
3                       Pixel 3a                      Pixel 3a   
4                      iPhone 11                     iPhone 11   

  visitor_device_hardware_vendor visitor_device_os_family  ...  \
0                            BLU                  Android  ...   
1                        Samsung                  Android  ...   
2                          Apple                    macOS  ...   
3                         Google                  Android  ...   
4                          Apple                      iOS  ...   

  visitor_geo_location_connection_type visitor_geo_location_countryCode  \
0                             Cellular                               US   
1                            Cable/DSL                               US   
2                            Cable/DSL                               US   
3                            Corporate                               US   
4                            Corporate                               US   

   visitor_geo_location_isp visitor_geo_location_regionName  \
0          Verizon Wireless                        New York   
1                  Spectrum                      California   
2        Cox Communications                        Virginia   
3               CenturyLink                         Arizona   
4  Clearwave Communications                        Illinois   

            visitor_tokens_adh visitor_tokens_cadid visitor_tokens_adi  \
0       regwillcoverinzipcodes           Otly1SNLj0       solarpergola   
1     regwillcoverowninzipcode            2SUr_THGD       blondejudge2   
2  reggovcovercostownhomeinzip           4RY0zVSNww       blondejudge2   
3  reggovcovercostownhomeinzip           WgXFI4Uq-I       blondejudge2   
4  reggovcovercostownhomeinzip           lzld1mh6bi       blondejudge2   

  visitor_tokens_add converted_yes converted_no  
0                NaN             0            1  
1                NaN             1            0  
2                NaN             0            1  
3                NaN             1            0  
4                NaN             1            0  

[5 rows x 24 columns]

In [5]:
df.dtypes

_id                                     object
landing_pages_group_id                  object
campaign_id                             object
landing_page_id                         object
traffic_source_id                       object
visitor_device_browser                  object
visitor_device_hardware_family          object
visitor_device_hardware_model           object
visitor_device_hardware_vendor          object
visitor_device_os_family                object
visitor_device_os_vendor                object
visitor_device_os_version               object
visitor_device_type                     object
visitor_geo_location_cityName           object
visitor_geo_location_connection_type    object
visitor_geo_location_countryCode        object
visitor_geo_location_isp                object
visitor_geo_location_regionName         object
visitor_tokens_adh                      object
visitor_tokens_cadid                    object
visitor_tokens_adi                      object
visitor_token

In [6]:
df["visitor_device_hardware_family"] = df["visitor_device_hardware_family"].apply(str)
df["visitor_device_hardware_model"] = df["visitor_device_hardware_model"].apply(str)
df["visitor_device_os_version"] = df["visitor_device_os_version"].apply(str)
df["visitor_device_hardware_family"] = df["visitor_device_hardware_family"].apply(str)
df["visitor_device_hardware_model"] = df["visitor_device_hardware_model"].apply(str)
df["visitor_device_os_version"] = df["visitor_device_os_version"].apply(str)
df["visitor_tokens_adh"] = df["visitor_tokens_adh"].apply(str)
df["visitor_tokens_cadid"] = df["visitor_tokens_cadid"].apply(str)
df["converted_yes"] = df["converted_yes"].apply(str)
df["converted_no"] = df["converted_no"].apply(str)

In [7]:
#!pip install sweetviz

In [8]:
#import sweetviz as sv

In [9]:
# Generar el reporte
#sweet_report = sv.analyze(df)

In [10]:
# Se muestra la salida
#sweet_report.show_notebook()

In [11]:
df.isna().sum().sort_values()

_id                                        0
visitor_tokens_cadid                       0
visitor_tokens_adh                         0
visitor_device_type                        0
converted_yes                              0
visitor_device_os_vendor                   0
visitor_device_os_family                   0
visitor_device_hardware_vendor             0
visitor_device_os_version                  0
visitor_device_hardware_family             0
visitor_device_browser                     0
traffic_source_id                          0
landing_page_id                            0
campaign_id                                0
landing_pages_group_id                     0
visitor_device_hardware_model              0
converted_no                               0
visitor_geo_location_countryCode           3
visitor_geo_location_regionName            3
visitor_tokens_adi                         8
visitor_geo_location_isp                 101
visitor_geo_location_connection_type     102
visitor_ge

In [12]:
df.shape

(6057, 24)

In [13]:
df = df.drop(['landing_pages_group_id','visitor_tokens_add', '_id'], axis=1)

In [14]:
df = df.drop_duplicates()

In [15]:
df.isna().sum().sort_values()

campaign_id                               0
visitor_tokens_cadid                      0
visitor_tokens_adh                        0
converted_yes                             0
visitor_device_os_version                 0
visitor_device_os_vendor                  0
visitor_device_os_family                  0
visitor_device_type                       0
visitor_device_hardware_model             0
visitor_device_hardware_family            0
visitor_device_browser                    0
traffic_source_id                         0
landing_page_id                           0
visitor_device_hardware_vendor            0
converted_no                              0
visitor_geo_location_countryCode          3
visitor_geo_location_regionName           3
visitor_tokens_adi                        6
visitor_geo_location_isp                 69
visitor_geo_location_connection_type     70
visitor_geo_location_cityName           141
dtype: int64

In [16]:
df.shape

(5909, 21)

In [17]:
# Imputamos la variable 
df['visitor_geo_location_countryCode'].fillna(df['visitor_geo_location_countryCode'].mode()[0], inplace=True)
df['visitor_geo_location_regionName'].fillna(df['visitor_geo_location_regionName'].mode()[0], inplace=True)
df['visitor_tokens_adi'].fillna(df['visitor_tokens_adi'].mode()[0], inplace=True)
df['visitor_geo_location_isp'].fillna(df['visitor_geo_location_isp'].mode()[0], inplace=True)
df['visitor_geo_location_connection_type'].fillna(df['visitor_geo_location_connection_type'].mode()[0], inplace=True)
df['visitor_geo_location_cityName'].fillna(df['visitor_geo_location_cityName'].mode()[0], inplace=True)

In [18]:
df.shape

(5909, 21)

In [19]:
df.isna().sum().sort_values()

campaign_id                             0
visitor_tokens_adi                      0
visitor_tokens_cadid                    0
visitor_tokens_adh                      0
visitor_geo_location_regionName         0
visitor_geo_location_isp                0
visitor_geo_location_countryCode        0
visitor_geo_location_connection_type    0
visitor_geo_location_cityName           0
converted_yes                           0
visitor_device_type                     0
visitor_device_os_vendor                0
visitor_device_os_family                0
visitor_device_hardware_vendor          0
visitor_device_hardware_model           0
visitor_device_hardware_family          0
visitor_device_browser                  0
traffic_source_id                       0
landing_page_id                         0
visitor_device_os_version               0
converted_no                            0
dtype: int64

In [20]:
df.columns

Index(['campaign_id', 'landing_page_id', 'traffic_source_id',
       'visitor_device_browser', 'visitor_device_hardware_family',
       'visitor_device_hardware_model', 'visitor_device_hardware_vendor',
       'visitor_device_os_family', 'visitor_device_os_vendor',
       'visitor_device_os_version', 'visitor_device_type',
       'visitor_geo_location_cityName', 'visitor_geo_location_connection_type',
       'visitor_geo_location_countryCode', 'visitor_geo_location_isp',
       'visitor_geo_location_regionName', 'visitor_tokens_adh',
       'visitor_tokens_cadid', 'visitor_tokens_adi', 'converted_yes',
       'converted_no'],
      dtype='object')

In [21]:
X = df[['campaign_id', 'traffic_source_id',
       'visitor_device_browser', 
        'visitor_device_type',
        'visitor_geo_location_countryCode',
       'visitor_geo_location_regionName', 'visitor_tokens_adh',
       'visitor_tokens_cadid', 'visitor_tokens_adi']]

In [22]:
X = X.astype(str).to_numpy()

In [23]:
y = df[["landing_page_id"]].to_numpy()

In [24]:
# encode string input values as integers
encoded_x = None
for i in range(0, X.shape[1]):
    label_encoder = LabelEncoder()
    feature = label_encoder.fit_transform(X[:,i])
    feature = feature.reshape(X.shape[0], 1)
    onehot_encoder = OrdinalEncoder()
    feature = onehot_encoder.fit_transform(feature)
    if encoded_x is None:
        encoded_x = feature
    else:
        encoded_x = numpy.concatenate((encoded_x, feature), axis=1)
print("X shape: : ", encoded_x.shape)


X shape: :  (5909, 9)


In [25]:
encoded_x

array([[ 26.,   5.,   3., ...,  18.,  69.,   9.],
       [  6.,   4.,   3., ...,  20.,   8.,   1.],
       [ 23.,   4.,  33., ...,  12.,  17.,   1.],
       ...,
       [  2.,   0.,   3., ...,  20., 110.,   0.],
       [ 22.,   4.,   3., ...,  12.,  82.,   2.],
       [ 22.,   4.,   3., ...,  20., 114.,   1.]])

In [26]:
# encode string class values as integers
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(y)
label_encoded_y = label_encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(label_encoded_y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:
label_encoded_y

array([0, 0, 2, ..., 1, 0, 0])

In [28]:
dummy_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [29]:
# split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(encoded_x, dummy_y, test_size=0.30, random_state=123)

In [30]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [31]:
# Definición del modelo
def modelo_mlp(): 
    model = Sequential()
    model.add(Dense(30, input_dim=X_train.shape[1], 
                kernel_initializer= 'he_uniform',
                activation='relu', activity_regularizer=regularizers.l1(1e-4)))
    model.add(BatchNormalization())
    model.add(Dense(15, kernel_initializer= 'he_uniform',
                activation='relu',activity_regularizer=regularizers.l1(1e-4)))
    model.add(Dropout(0.2))
    model.add(BatchNormalization())
    model.add(Dense(10, kernel_initializer= 'he_uniform',
                activation='relu',activity_regularizer=regularizers.l1(1e-4)))
    model.add(Dropout(0.2))
    model.add(BatchNormalization())  
    model.add(Dense(3, kernel_initializer= 'he_uniform',
                activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam',
                metrics=['accuracy'])
    #model.summary()
    return model

In [32]:
model = modelo_mlp()

In [33]:
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [34]:
estimator = KerasClassifier(build_fn=modelo_mlp, epochs=100, batch_size=32, verbose=0)
kfold = KFold(n_splits=10, shuffle=True)
results = cross_val_score(estimator, X_train, y_train, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  """Entry point for launching an IPython kernel.


Baseline: 44.88% (2.98%)


In [52]:
estimator.fit(X_train, y_train)

In [53]:
predictions = estimator.predict(X_test)
print(predictions)
print(label_encoder.inverse_transform(predictions))

56/56 [==============================] - 1s 2ms/step
[1 2 0 ... 0 2 1]
['6377333cb20e47001a2057c0' '637735d9b20e47001a2057c1'
 '62566aa432b19a0164d802be' ... '62566aa432b19a0164d802be'
 '637735d9b20e47001a2057c1' '6377333cb20e47001a2057c0']


In [54]:
predictions = estimator.predict(X_test[1:2])
print(predictions)
print(label_encoder.inverse_transform(predictions))

1/1 [==============================] - 0s 17ms/step
[2]
['637735d9b20e47001a2057c1']


In [56]:
predictions = estimator.predict(X_test[10:11])
print(predictions)
print(label_encoder.inverse_transform(predictions))

1/1 [==============================] - 0s 22ms/step
[1]
['6377333cb20e47001a2057c0']


In [59]:
predictions = estimator.predict(X_test[50:51])
print(predictions)
print(label_encoder.inverse_transform(predictions))

1/1 [==============================] - 0s 16ms/step
[0]
['62566aa432b19a0164d802be']


In [35]:
# Entrenamos el modelo con el dataset
#history=model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test), shuffle=False)

In [36]:
#loss, accuracy = model.evaluate(X_train, y_train, verbose=False)
#print("Precisión Entrenamiento: {:.4f}".format(accuracy))
#loss, accuracy = model.evaluate(X_test, y_test, verbose=False)
#print("Precisión Prueba:  {:.4f}".format(accuracy))

In [37]:
#from matplotlib import pyplot
#from numpy import array
# plot train and validation loss
#pyplot.plot(history.history['loss'])
#pyplot.plot(history.history['val_loss'])
#pyplot.title('model train vs validation loss')
#pyplot.ylabel('loss')
#pyplot.xlabel('epoch')
#pyplot.legend(['train', 'validation'], loc='upper right')
#pyplot.show()

In [38]:
#Making confusion matrix that checks accuracy of the model
#from sklearn.metrics import confusion_matrix
#from sklearn.metrics import ConfusionMatrixDisplay

In [39]:
#y_pred=model.predict(X_test) 
#y_pred=np.argmax(y_pred, axis=1)
#y_test=np.argmax(y_test, axis=1)
#cm = confusion_matrix(y_test, y_pred)
#disp = ConfusionMatrixDisplay(confusion_matrix=cm)
#disp.plot()

#plt.show()

In [40]:
#from sklearn.metrics import classification_report
#report = classification_report(y_test, y_pred)
#print(report)

In [41]:
# make class predictions with the model
#predictions = (model.predict(X_test[1:2]))
#predictions

In [42]:
# make class predictions with the model
#predictions = (model.predict(X_test[1:2])).argmax(1)
#predictions

In [43]:
#print(label_encoder.inverse_transform(predictions))

In [44]:
#from keras.models import load_model 
#model.save("model_6377366a6f84e2001a65fdfe.h5") 
#loaded_model = load_model("model_6377366a6f84e2001a65fdfe.h5")

In [45]:
# make class predictions with the model
#predictions = (model.predict(X_test[1:2]))
#predictions

In [46]:
# make class predictions with the model
#predictions = (loaded_model.predict(X_test[1:2])).argmax(1)
#predictions

In [47]:
#rint(label_encoder.inverse_transform(predictions))