<a href="https://colab.research.google.com/github/GUILLENJV/62f1ab79cc287b001f643389/blob/master/Model_Tensorflow_Softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Model_Tensorflow
# Multilayer
# Softmax

In [1]:
# Load Libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, label_binarize
from sklearn.model_selection import train_test_split
import requests
from sklearn import datasets
from sklearn import preprocessing
from collections import defaultdict
from sklearn.preprocessing import normalize
from tensorflow.python.framework import ops
ops.reset_default_graph()

##  Load Dataset 

In [2]:
df= pd.read_excel('631d8277776f1d001a21e6eb_120922.xlsx')

In [3]:
df.head()

campaign_id         traffic_source_id visitor_device_browser  \
0  5cb4f2dfc38c333c70c4c7e2  57ac89e0a38746122f4af882                 Safari   
1  5cb4f2dfc38c333c70c4c7e2  57ac89e0a38746122f4af882        Unknown Crawler   
2  59d7e4bd8f21b57977a85a41  591b6c25321d75857258a641                 Safari   
3  59d7e4bd8f21b57977a85a41  591b6c25321d75857258a641                Unknown   
4  59d7e4bd8f21b57977a85a41  591b6c25321d75857258a641   Facebook for Android   

  visitor_device_hardware_family visitor_device_hardware_model  \
0                      Macintosh                     Macintosh   
1                      Macintosh                     Macintosh   
2                      Macintosh                     Macintosh   
3                       Emulator                       Unknown   
4                            One                          ONE    

  visitor_device_hardware_vendor visitor_device_os_family  \
0                          Apple                    macOS   
1                          Apple                    macOS   
2                          Apple                 Mac OS X   
3                        Unknown                  Unknown   
4                            HTC                  Android   

  visitor_device_os_vendor visitor_device_os_version visitor_device_type  ...  \
0                    Apple                   10.15.7             Desktop  ...   
1                    Apple                   10.15.5             Desktop  ...   
2                    Apple                   10.10.1             Desktop  ...   
3                  Unknown                   Unknown             Desktop  ...   
4                   Google                     4.4.4               Phone  ...   

  visitor_geo_location_connection_type visitor_geo_location_countryCode  \
0                            Corporate                               IE   
1                                  NaN                               US   
2                            Corporate                               US   
3                                  NaN                               US   
4                            Corporate                               US   

  visitor_geo_location_isp visitor_geo_location_regionName  \
0               Amazon.com                        Leinster   
1                      NaN                      California   
2               Amazon.com                        Virginia   
3                      NaN                        New York   
4    Cogent Communications            District of Columbia   

     visitor_tokens_adh visitor_tokens_cadid visitor_tokens_adi converted_yes  \
0  rebatepayinstall-ymq          1FJgQpbZdX0          solaryard             0   
1  rebatepayinstall-ymq          1FJgQpbZdX0          solaryard             0   
2                   NaN                  NaN                NaN             0   
3                   NaN                  NaN                NaN             0   
4                   NaN                  NaN                NaN             0   

   converted_no           landing_page_id  
0             1  631d72ff99ba21001a8503fa  
1             1  631d779999ba21001a850416  
2             1  631d779999ba21001a850416  
3             1  631d72ff99ba21001a8503fa  
4             1  631d72ff99ba21001a8503fa  

[5 rows x 21 columns]

#  Data preprocessing

In [4]:
df["landing_page_id"].value_counts()

631d72ff99ba21001a8503fa    499
631d779999ba21001a850416    499
62566aa432b19a0164d802be    499
Name: landing_page_id, dtype: int64

In [5]:
df.dtypes

campaign_id                             object
traffic_source_id                       object
visitor_device_browser                  object
visitor_device_hardware_family          object
visitor_device_hardware_model           object
visitor_device_hardware_vendor          object
visitor_device_os_family                object
visitor_device_os_vendor                object
visitor_device_os_version               object
visitor_device_type                     object
visitor_geo_location_cityName           object
visitor_geo_location_connection_type    object
visitor_geo_location_countryCode        object
visitor_geo_location_isp                object
visitor_geo_location_regionName         object
visitor_tokens_adh                      object
visitor_tokens_cadid                    object
visitor_tokens_adi                      object
converted_yes                            int64
converted_no                             int64
landing_page_id                         object
dtype: object

In [6]:
df["visitor_device_hardware_family"] = df["visitor_device_hardware_family"].apply(str)
df["visitor_device_hardware_model"] = df["visitor_device_hardware_model"].apply(str)
df["visitor_device_os_version"] = df["visitor_device_os_version"].apply(str)
df["visitor_device_hardware_family"] = df["visitor_device_hardware_family"].apply(str)
df["visitor_device_hardware_model"] = df["visitor_device_hardware_model"].apply(str)
df["visitor_device_os_version"] = df["visitor_device_os_version"].apply(str)
df["visitor_tokens_adh"] = df["visitor_tokens_adh"].apply(str)
df["visitor_tokens_cadid"] = df["visitor_tokens_cadid"].apply(str)
df["converted_yes"] = df["converted_yes"].apply(str)
df["converted_no"] = df["converted_no"].apply(str)
df["converted_yes"] = df["converted_yes"].apply(str)
df["converted_no"] = df["converted_no"].apply(str)

In [7]:
df.dtypes

campaign_id                             object
traffic_source_id                       object
visitor_device_browser                  object
visitor_device_hardware_family          object
visitor_device_hardware_model           object
visitor_device_hardware_vendor          object
visitor_device_os_family                object
visitor_device_os_vendor                object
visitor_device_os_version               object
visitor_device_type                     object
visitor_geo_location_cityName           object
visitor_geo_location_connection_type    object
visitor_geo_location_countryCode        object
visitor_geo_location_isp                object
visitor_geo_location_regionName         object
visitor_tokens_adh                      object
visitor_tokens_cadid                    object
visitor_tokens_adi                      object
converted_yes                           object
converted_no                            object
landing_page_id                         object
dtype: object

In [8]:
df.isna().sum().sort_values()

campaign_id                              0
converted_yes                            0
visitor_tokens_cadid                     0
visitor_tokens_adh                       0
visitor_geo_location_regionName          0
visitor_geo_location_countryCode         0
converted_no                             0
visitor_device_type                      0
landing_page_id                          0
visitor_device_os_vendor                 0
visitor_device_os_family                 0
visitor_device_hardware_vendor           0
visitor_device_hardware_model            0
visitor_device_hardware_family           0
visitor_device_browser                   0
traffic_source_id                        0
visitor_device_os_version                0
visitor_tokens_adi                       5
visitor_geo_location_isp                12
visitor_geo_location_connection_type    14
visitor_geo_location_cityName           40
dtype: int64

In [9]:
# Imputamos la variable 
df['visitor_geo_location_isp'].fillna(df['visitor_geo_location_isp'].mode()[0], inplace=True)
df['visitor_geo_location_connection_type'].fillna(df['visitor_geo_location_connection_type'].mode()[0], inplace=True)
df['visitor_geo_location_cityName'].fillna(df['visitor_geo_location_cityName'].mode()[0], inplace=True)
df['visitor_tokens_adi'].fillna(df['visitor_tokens_adi'].mode()[0], inplace=True)

In [10]:
df.isna().sum().sort_values()

campaign_id                             0
converted_yes                           0
visitor_tokens_adi                      0
visitor_tokens_cadid                    0
visitor_tokens_adh                      0
visitor_geo_location_regionName         0
visitor_geo_location_isp                0
visitor_geo_location_countryCode        0
visitor_geo_location_connection_type    0
converted_no                            0
visitor_geo_location_cityName           0
visitor_device_os_version               0
visitor_device_os_vendor                0
visitor_device_os_family                0
visitor_device_hardware_vendor          0
visitor_device_hardware_model           0
visitor_device_hardware_family          0
visitor_device_browser                  0
traffic_source_id                       0
visitor_device_type                     0
landing_page_id                         0
dtype: int64

#  Label Encode

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df.columns

Index(['campaign_id', 'traffic_source_id', 'visitor_device_browser',
       'visitor_device_hardware_family', 'visitor_device_hardware_model',
       'visitor_device_hardware_vendor', 'visitor_device_os_family',
       'visitor_device_os_vendor', 'visitor_device_os_version',
       'visitor_device_type', 'visitor_geo_location_cityName',
       'visitor_geo_location_connection_type',
       'visitor_geo_location_countryCode', 'visitor_geo_location_isp',
       'visitor_geo_location_regionName', 'visitor_tokens_adh',
       'visitor_tokens_cadid', 'visitor_tokens_adi', 'converted_yes',
       'converted_no', 'landing_page_id'],
      dtype='object')

In [13]:
X = df[['campaign_id', 'traffic_source_id', 'visitor_device_browser',
       'visitor_device_hardware_family', 'visitor_device_hardware_model',
       'visitor_device_hardware_vendor', 'visitor_device_os_family',
       'visitor_device_os_vendor', 'visitor_device_os_version',
       'visitor_device_type', 'visitor_geo_location_cityName',
       'visitor_geo_location_connection_type',
       'visitor_geo_location_countryCode', 'visitor_geo_location_isp',
       'visitor_geo_location_regionName', 'visitor_tokens_adh',
       'visitor_tokens_cadid', 'visitor_tokens_adi', 'converted_yes',
       'converted_no']]

In [14]:
X = X.astype(str).to_numpy()

In [15]:
y = df[["landing_page_id"]].to_numpy()

In [16]:
X

array([['5cb4f2dfc38c333c70c4c7e2', '57ac89e0a38746122f4af882', 'Safari',
        ..., 'solaryard', '0', '1'],
       ['5cb4f2dfc38c333c70c4c7e2', '57ac89e0a38746122f4af882',
        'Unknown Crawler', ..., 'solaryard', '0', '1'],
       ['59d7e4bd8f21b57977a85a41', '591b6c25321d75857258a641', 'Safari',
        ..., 'tsbatout', '0', '1'],
       ...,
       ['630e3a6e050023001a6696ff', '5e46d6787810b90011c91204', 'Safari',
        ..., 'blondejudge2', '1', '0'],
       ['630e3a6e050023001a6696ff', '5e46d6787810b90011c91204', 'Safari',
        ..., 'blondejudge2', '1', '0'],
       ['630e3a6e050023001a6696ff', '5e46d6787810b90011c91204', 'Safari',
        ..., 'blondejudge2', '1', '0']], dtype=object)

In [17]:
y

array([['631d72ff99ba21001a8503fa'],
       ['631d779999ba21001a850416'],
       ['631d779999ba21001a850416'],
       ...,
       ['631d72ff99ba21001a8503fa'],
       ['631d72ff99ba21001a8503fa'],
       ['631d72ff99ba21001a8503fa']], dtype=object)

In [18]:
# encode string input values as integers
encoded_x = None
for i in range(0, X.shape[1]):
    label_encoder = LabelEncoder()
    feature = label_encoder.fit_transform(X[:,i])
    feature = feature.reshape(X.shape[0], 1)
    onehot_encoder = OrdinalEncoder()
    feature = onehot_encoder.fit_transform(feature)
    if encoded_x is None:
        encoded_x = feature
    else:
        encoded_x = np.concatenate((encoded_x, feature), axis=1)
print("X shape: : ", encoded_x.shape)

X shape: :  (1497, 20)


In [19]:
encoded_x

array([[ 1.,  0., 18., ...,  9.,  0.,  1.],
       [ 1.,  0., 23., ...,  9.,  0.,  1.],
       [ 0.,  3., 18., ..., 10.,  0.,  1.],
       ...,
       [33.,  4., 18., ...,  1.,  1.,  0.],
       [33.,  4., 18., ...,  1.,  1.,  0.],
       [33.,  4., 18., ...,  1.,  1.,  0.]])

In [20]:
from keras.utils import np_utils

In [21]:
# encode string class values as integers
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(y)
label_encoded_y = label_encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(label_encoded_y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
dummy_y

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

##  Split Data

In [23]:
# split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(encoded_x, dummy_y , test_size=0.20, random_state=123)

In [24]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(1197, 20) (300, 20)
(1197, 3) (300, 3)


In [25]:
# Normalize by column (min-max norm)
def normalize_cols(m):
    col_max = m.max(axis=0)
    col_min = m.min(axis=0)
    return (m-col_min) / (col_max - col_min)
    
X_vals_train = np.nan_to_num(normalize_cols(X_train))
X_vals_test = np.nan_to_num(normalize_cols(X_test))

In [26]:
X_vals_train

array([[0.87878788, 0.83333333, 0.24      , ..., 0.09090909, 1.        ,
        0.        ],
       [0.27272727, 0.        , 0.24      , ..., 0.54545455, 1.        ,
        0.        ],
       [0.3030303 , 0.        , 0.08      , ..., 0.54545455, 1.        ,
        0.        ],
       ...,
       [0.87878788, 0.83333333, 0.24      , ..., 0.09090909, 1.        ,
        0.        ],
       [0.87878788, 0.83333333, 0.04      , ..., 0.09090909, 1.        ,
        0.        ],
       [0.87878788, 0.83333333, 0.24      , ..., 0.09090909, 1.        ,
        0.        ]])

## Define Tensorflow computational graph

In [27]:
import tensorflow.compat.v1 as tf

In [28]:
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [29]:
# Declare batch size
batch_size = 90

In [30]:
# Create graph
sess = tf.Session()

# Initialize placeholders
x_data = tf.placeholder(shape=[None, 20], dtype=tf.float32)
y_target = tf.placeholder(shape=[None, 3], dtype=tf.float32)

In [31]:
# Create variables for linear regression
W = tf.Variable(tf.zeros(shape=[20,3]))
b = tf.Variable(tf.zeros([3]))

In [32]:
# Declare model operations
y = tf.nn.softmax(tf.matmul(x_data, W) + b)

In [33]:
# Declare loss function (Cross Entropy loss)
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_target * tf.log(y), reduction_indices=[1]))

In [34]:
# Declare optimizer
train_step = tf.train.AdamOptimizer(0.0001).minimize(cross_entropy)

In [35]:
# Actual Prediction
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_target, 1))

In [36]:
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# Train model

In [37]:
# Create graph session 
sess = tf.Session()
# Initialize variables
init = tf.global_variables_initializer()
sess.run(init)

In [38]:
sess.run(train_step, feed_dict={x_data: X_train, y_target: [t for t in y_train]})
sess.run(cross_entropy, feed_dict={x_data: X_train, y_target: [t for t in y_train]})
#sess.run(W,b)
for i in range(0,5000):
  _, C = sess.run([train_step, cross_entropy],  feed_dict={x_data: X_train, y_target: [t for t in y_train]})
  if i %500 ==0:
    print("loss >>>", C)

print("aacuaracy >>>", sess.run(accuracy*100, feed_dict={x_data: X_test, y_target: [t for t in y_test]}))

loss >>> 1.0960603
loss >>> 0.7683605
loss >>> 0.7116641
loss >>> 0.6905328
loss >>> 0.6797256
loss >>> 0.6730488
loss >>> 0.66822517
loss >>> 0.66445166
loss >>> 0.6612314
loss >>> 0.6584137
aacuaracy >>> 61.333336


In [39]:
new_data  = X_test[100:101]
new_data

array([[ 23.,   5.,   6.,  17., 147.,  19.,   4.,   3.,  54.,   0., 282.,
          0.,   3., 119.,   3.,   3.,  92.,   4.,   1.,   0.]])

In [40]:
val = sess.run(tf.argmax(y, 1), feed_dict={x_data:new_data})[0]
#new_predict = y.inverse_transform(val)[0]
print('New Data Predictions: {}'.format(val))
if val == 0:
  print('631d72ff99ba21001a8503fa')
elif val == 1:
  print('631d779999ba21001a850416')
elif val == 2:
  print('62566aa432b19a0164d802be')

New Data Predictions: 2
62566aa432b19a0164d802be
